Plugin\PayJp\Entity\PayJpConfig:
    type: entity
    table: plg_pay_jp_config
    repositoryClass: Plugin\PayJp\Repository\PayJpTokenRepository
    id:
        id:
            type: integer
            nullable: false
            id: true
            column: id
            generator:
                strategy: NONE
    fields:
        api_key_secret:
            type: string
            nullable: false
        created_at:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }